[package]
description = "Fixed-size buffer for networking protocols."
documentation = "https://docs.rs/fixedbuf"
edition = "2024"
license = "MIT"
name = "fixedbuf"
repository = "https://github.com/ZeroRtt/ZeroRtt/crates/fixedbuf"
version = "0.1.2"

[dependencies]
