[package]
description = "A lightweight metrics facade for `Rust`."
documentation = "https://docs.rs/metricrs"
edition = "2024"
license = "MIT"
name = "metricrs"
repository = "https://github.com/ZeroRtt/ZeroRtt/crates/metrics"
version = "0.1.0"


[dependencies]
