[package]
description = "non-blocking I/O beyound rust asynchronous runtimes."
documentation = "https://docs.rs/zerio"
edition = "2024"
license = "MIT"
name = "zerio"
repository = "https://github.com/ZeroRtt/ZeroRtt/zerio"
version = "0.1.0"
edition = "2024"

[dependencies]
