[package]
description = "An experimental structured concurrency runtime for Rust."
documentation = "https://docs.rs/zerio"
edition = "2024"
license = "MIT"
name = "zerio"
repository = "https://github.com/ZeroRtt/ZeroRtt/zerio"
version = "0.1.0"

[dependencies]
log = { version = "^0.4" }
thiserror = "^2.0"
futures-channel = "^0.3"
futures-task = "^0.3"
num_cpus = "^1.17"
parking_lot = "^0.12"
crossbeam = { version="0.8.4", optional = true }

[features]
default = ["executor","thread-pool"]
executor = []
thread-pool = ["crossbeam"]
